import React, { useState } from 'react';
import { useAppStore } from '../store/appStore';
import { uploadDocument, generateSummary } from '../services/api';
import { Card, Button, FormGroup, Label, Input, Spinner, Alert, ProgressBar } from '../components/UI';
import { DocumentUploader, SummaryDisplay } from '../components/SpecializedComponents';

const UploadSummarizePage = () => {
  const { addDocument, addSummary, addToHistory, setLoading, loading } = useAppStore();
  const [file, setFile] = useState(null);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [summary, setSummary] = useState(null);
  const [summaryOptions, setSummaryOptions] = useState({
    maxLength: 150,
    minLength: 50,
  });
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const [step, setStep] = useState(1); // 1: Upload, 2: Options, 3: Results

  const handleFileSelect = async (selectedFile) => {
    setFile(selectedFile);
    setStep(2);
    setError(null);

    // Simulate file upload
    setLoading(true);
    try {
      // In a real app, you'd call uploadDocument here
      const documentData = {
        id: Date.now().toString(),
        name: selectedFile.name,
        size: selectedFile.size,
        type: selectedFile.type,
        uploadedAt: new Date().toISOString(),
      };

      addDocument(documentData);
      addToHistory({
        id: Date.now().toString(),
        type: 'upload',
        title: selectedFile.name,
        status: 'success',
      });

      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateSummary = async () => {
    if (!file) return;

    setLoading(true);
    setError(null);

    try {
      // In a real app, you'd call generateSummary with the file ID
      const mockSummary = `This is a placeholder summary of the uploaded document. 
        In a production environment, this would be generated by the backend API 
        using advanced NLP techniques. The summary would extract key points and 
        concepts from the full text while maintaining context and readability.`;

      setSummary({
        text: mockSummary,
        originalText: 'Full document text would appear here...',
        metrics: {
          compression: Math.round((mockSummary.length / 5000) * 100),
          processingTime: 2.5,
          tokensUsed: 1024,
          wordCount: mockSummary.split(' ').length,
        },
      });

      addSummary(file.name, mockSummary);
      addToHistory({
        id: Date.now().toString(),
        type: 'summary',
        title: file.name,
        status: 'success',
      });

      setStep(3);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(summary.text);
    setSuccess(true);
    setTimeout(() => setSuccess(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([summary.text], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'summary.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Upload & Summarize</h1>
        <p className="text-gray-600 dark:text-gray-400">
          Upload your research papers and get instant intelligent summaries
        </p>
      </div>

      {/* Alerts */}
      {error && (
        <Alert
          type="error"
          title="Error"
          message={error}
          onClose={() => setError(null)}
        />
      )}
      {success && (
        <Alert type="success" message="Action completed successfully!" />
      )}

      {/* Step Indicator */}
      <div className="flex gap-4 justify-center">
        {[1, 2, 3].map((s) => (
          <div key={s} className="flex items-center">
            <div
              className={`w-10 h-10 rounded-full flex items-center justify-center font-bold transition-colors ${
                step >= s
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-300 dark:bg-gray-600 text-gray-600 dark:text-gray-400'
              }`}
            >
              {s}
            </div>
            {s < 3 && <div className="w-12 h-1 mx-2 bg-gray-300 dark:bg-gray-600"></div>}
          </div>
        ))}
      </div>

      {/* Step 1: Upload */}
      {step === 1 && (
        <DocumentUploader onFileSelect={handleFileSelect} />
      )}

      {/* Step 2: Configure Summary Options */}
      {step === 2 && file && (
        <div className="space-y-6">
          <Card>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">
              Configure Summary Options
            </h2>

            <div className="space-y-6">
              {/* File Info */}
              <div className="p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
                <p className="text-sm text-gray-600 dark:text-gray-400">Selected File</p>
                <p className="font-semibold text-gray-900 dark:text-white">{file.name}</p>
                <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                  {(file.size / 1024 / 1024).toFixed(2)} MB
                </p>
              </div>

              {/* Max Length */}
              <FormGroup label={`Maximum Summary Length: ${summaryOptions.maxLength} words`}>
                <input
                  type="range"
                  min="50"
                  max="500"
                  value={summaryOptions.maxLength}
                  onChange={(e) =>
                    setSummaryOptions((prev) => ({
                      ...prev,
                      maxLength: parseInt(e.target.value),
                    }))
                  }
                  className="w-full"
                />
                <p className="text-xs text-gray-600 dark:text-gray-400 mt-2">
                  Recommended: 100-250 words for a balanced summary
                </p>
              </FormGroup>

              {/* Min Length */}
              <FormGroup label={`Minimum Summary Length: ${summaryOptions.minLength} words`}>
                <input
                  type="range"
                  min="20"
                  max="200"
                  value={summaryOptions.minLength}
                  onChange={(e) =>
                    setSummaryOptions((prev) => ({
                      ...prev,
                      minLength: parseInt(e.target.value),
                    }))
                  }
                  className="w-full"
                />
              </FormGroup>

              {/* Compression Ratio */}
              <div className="p-4 bg-blue-50 dark:bg-blue-900 rounded-lg border border-blue-200 dark:border-blue-800">
                <p className="text-sm font-medium text-blue-900 dark:text-blue-200 mb-2">
                  Estimated Compression
                </p>
                <ProgressBar value={75} max={100} showLabel={true} />
              </div>

              {/* Action Buttons */}
              <div className="flex gap-4 pt-6 border-t border-gray-200 dark:border-gray-700">
                <Button variant="outline" onClick={() => setStep(1)}>
                  ← Change File
                </Button>
                <Button
                  variant="primary"
                  fullWidth
                  loading={loading}
                  onClick={handleGenerateSummary}
                >
                  Generate Summary
                </Button>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* Step 3: Display Summary */}
      {step === 3 && summary && (
        <SummaryDisplay
          summary={summary.text}
          originalText={summary.originalText}
          metrics={summary.metrics}
          onCopy={handleCopy}
          onDownload={handleDownload}
          onSave={() => {
            setSuccess(true);
            setTimeout(() => setSuccess(false), 2000);
          }}
        />
      )}

      {/* Tips Section */}
      {step === 1 && (
        <Card className="bg-blue-50 dark:bg-blue-900 border border-blue-200 dark:border-blue-800">
          <h3 className="text-lg font-semibold text-blue-900 dark:text-blue-200 mb-4">
            💡 Tips for Best Results
          </h3>
          <ul className="space-y-2 text-sm text-blue-900 dark:text-blue-200">
            <li>• Supports PDF, TXT, and DOCX files up to 10MB</li>
            <li>• Longer documents may take more time to process</li>
            <li>• Adjust summary length based on your needs</li>
            <li>• You can ask questions about the document after summarization</li>
          </ul>
        </Card>
      )}
    </div>
  );
};

export default UploadSummarizePage;
